export const productConfig = {
    title: "Product Database",
    tableHeader: [
      "Creator ID",
      "Creator Number",
      "Creator Mail",
      "Product ID",
      "Telegram Integration",
      "Whatsapp Integration",
      "Discord Integration",
      "Payment Page",
      "Course",
      "Event",
      "Community Name",
      "Free Group Name",
      "Paid Group Name",
      "Product Verification",
    ],
    tableData: [
      [
        "#CR12345",
        "+91 9801231230",
        "creator@gmail.com",
        "50500",
        {"label": "View info", "link": "https://ddd.com/johndoe"},
        {"label": "View info", "link": "https://www.com/johndoe"},
        {"label": "View info", "link": ""},
        {"label": "link", "link": "https://aaa.com/johndoe"},
        {"label": "link", "link": "https://eee.com/johndoe"},
        {"label": "link", "link": "https://ttt.com/johndoe"},
        "GenexX",
        "GenexX",
        "GenexX",
        "Approved",
      ],
    ],
  };